#!/usr/bin/env bash
# Stop 4-to_infinity_and_beyond process

# Find the PID of the process
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

# Check if the process is running
if [[ -n "$pid" ]]; then
  # Kill the process
  kill "$pid"
  echo "4-to_infinity_and_beyond process stopped"
else
  echo "4-to_infinity_and_beyond process is not running"
fi
