#!/usr/bin/env bash

# Find the process ID of the process we want to stop
PID=$(ps -ef | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

# Check if the process is running
if [ -z "$PID" ]; then
  echo "Process 4-to_infinity_and_beyond is not running"
else
  # Send SIGTERM signal to the process
  pkill -TERM -P "$PID"
  echo "Process 4-to_infinity_and_beyond has been stopped"
fi
