#!/usr/bin/env bash

# Bash script that displays numbers from 1 to 20 and:
# - displays "bad luck from China" after 4th iteration
# - displays "bad luck from Japan" after 9th iteration
# - displays "bad luck from Italy" after 17th iteration

for i in {1..20}; do
    echo $i
    case $i in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
done
